### ISSUE TITLE
Getting error in train.py

### ISSUE THREAD

**Issue by sayalijangam** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#2] opened 2019-01-23 06:27 UTC
Hi,
 Am referring your project but in train.py I getting one error as shown below. 
 **File "E:/Malicious-Web-Content-Detection-Using-Machine-Learning-master/train.py", line 14, in <module>
    data1 = data1[0:, : -1]

TypeError: list indices must be integers or slices, not tuple**

Also even tried to solve it....I don't get it the use of this snippet
**data1 = data1[0 : -1]
for i in data1:
    labels.append(i[30])**

**Comment by sayalijangam** [comment] 2019-01-28 05:09
3.6.4

**Comment by rohitnaik246** [comment] 2019-01-29 07:17
Probably that is the reason. This project was done using Python 2.7.
There are certain small differences between the two versions which might
cause this issue. Please try with Python 2.7

Thanks and regards,
Rohit Naik

**Comment by sayalijangam** [comment] 2019-01-30 10:04
Now I've done using python 2.7.....but still facing same [error``](https://drive.google.com/open?id=1LGB8eIwcsbXWFKVxY1BUqQY-bmqc0DFgWrQMoTCujZg)

You can see error using above link

**Comment by rohitnaik246** [comment] 2019-01-30 13:05
Hi Sayali,
It seems to be working fine on my end.
I tried replicating the situation with a much smaller data set just for representation purpose.

<img width="721" alt="screen shot 2019-01-30 at 6 18 02 pm" src="https://user-images.githubusercontent.com/18022447/51982306-a3f90100-24bb-11e9-9f4a-ff291bb618a6.png">
<img width="1280" alt="screen shot 2019-01-30 at 6 18 21 pm" src="https://user-images.githubusercontent.com/18022447/51982300-9e032000-24bb-11e9-9432-34a16f5d2e77.png">

1. Are you sure you are using Python 2.7 and not 3.x? There is a difference in how the file splitting is done in both so it is necessary that you have the correct version of Python. Otherwise you might face problems later as well. 
For Python3, ```data_list = file.split('\n')``` works but for Python2 ```data_list = file.split('\r\n')``` is needed for the correct split.
2. Can you please let me know what do you get for data1.shape similar to what I have done? That is probably the reason why you are getting that error, i.e. due to the mismatch of dimensions of the np array.
3. Also, please do a ```git pull``` and run this newly added file ```temp.py``` on your end and please attach the results if the problem persists.

Thanks

**Comment by rohitnaik246** [comment] 2019-02-10 12:36
I have revamped the entire project to remove certain deprecated method calls, improved certain aspects of the code. Please do a ```git pull``` on the project and try running it according to the [steps for reproducing the project](https://github.com/rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#steps-for-reproducing-the-project--).

Thanks

**Comment by rohitnaik246** [comment] 2019-02-24 20:15
Since, there has been no reply to this thread, I am closing it. Open up another issue if there is any problem.
Thanks!

**Closed by rohitnaik246** 2019-02-24 20:15 UTC
